services:
  db:
    image: mysql:8.0
    ports:
     - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypassword   
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
     - db_volumes:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  backend:
    build: .
    ports:
     - 8000:8000
    env_file:
      - .env
    volumes:
     - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
  db_volumes:
