# Generated by Django 5.1.1 on 2024-09-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_datetime_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-datetime_created']},
        ),
    ]
